### ISSUE TITLE
PlayerJoinEvent error

### ISSUE THREAD

**Issue by titanium63** [oliverdunk/JukeboxAPI#33]
Hello,
I have just install MCJukebox and worldguard 7.0.0 and i have that in my console :

> [11:36:23] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to MCJukebox v2.5.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
	at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onMove(RegionListener.java:59) ~[?:?]
	at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onJoin(RegionListener.java:38) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-c88ae6b]
	... 14 more

Could you fix that ? Thank you

**Comment by oliverdunk** [comment]
Hi,

We don't support MC 1.13 at the moment. We'd love to, but there is no official WorldEdit release for that version yet, because they still have performance issues to resolve.

I'm closing this since there's nothing we can do at the moment. Rest assured that as soon as WorldEdit is ready, we'll update MCJukebox too.
