### ISSUE TITLE
Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by XanderStoffels** [oliverdunk/JukeboxAPI#45]
Whenever a player moves, this error gets thrown:
 ```
[Server thread/ERROR]: Could not pass event PlayerMoveEvent to MCJukebox v2.6.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:985) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
        at net.mcjukebox.shared.wg7.RegionProvider.getApplicableRegions(RegionProvider.java:28) ~[?:?]
        at net.mcjukebox.plugin.bukkit.listeners.RegionListener.onMove(RegionListener.java:59) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
        ... 17 more
```

**Server**: Spigot 1.14.3
**Plugins**: WorldEdit, WorldGuard

Hope this helps fixing the problems for 1.14.*.

**Comment by oliverdunk** [comment]
Hi, could you check the version of WorldEdit and WorldGuard that you're using? This error isn't one I've seen before.

**Comment by XanderStoffels** [comment]
That would be the current latest builds:

<strong>[WorldEdit](https://dev.bukkit.org/projects/worldedit/files/2723275)</strong>: 7.0.0
<strong>[WorldGuard](https://dev.bukkit.org/projects/worldguard/files/2723606)</strong>: 7.0.0

**Comment by oliverdunk** [comment]
Unfortunately I haven't been able to reproduce it. Could you let me know if the problem persists after updating to MCJukebox v2.6.3 (this is only on the releases tab of GitHub currently)?

**Comment by XanderStoffels** [comment]
The problem persisted. However, if I remove WorldGuard, no exceptions are being thrown. I will look into it some more on my part.

**Comment by oliverdunk** [comment]
MCJukebox disables region integration when it doesn't detect WorldGuard, so that would explain what you're seeing. I trust you that you're having this problem, but it's strange that I'm not seeing it. If you don't find a solution after playing for a bit please email support@mcjukebox.net and I'll see what we can figure out to help.
